import * as assert from "assert";
import * as fs from "fs";
import { Chat, Message, WebMessageInfo } from "../whatsapp_pb";

const plainObj = {
    id: 'AEDF49F7E5FD1F',
    displayname: 'Sample Display Name'
}

const chat = new Chat();
chat.setDisplayname(plainObj.displayname)
chat.setId(plainObj.id)
const bin = chat.serializeBinary()
const chatRead = Chat.deserializeBinary(bin)
const obj = chatRead.toObject()
assert.equal(obj.displayname, plainObj.displayname)
assert.equal(obj.id, plainObj.id)

// This message is generated by WA Web when sending message, sent as action node
const buf = fs.readFileSync("etc/binary-sample/sent-message.proto.bin")
const msg = WebMessageInfo.deserializeBinary(buf)

assert.equal(msg.getStatus(), 1)
assert.equal(msg.getMessagetimestamp(), 1589871077)

assert.ok(msg.getKey())
assert.equal(msg.getKey().getRemotejid(), '628997026464@s.whatsapp.net')
assert.equal(msg.getKey().getFromme(), true)
// Where id come from?
assert.equal(msg.getKey().getId(), '3EB082A541839959E947')

assert.ok(msg.getMessage())
// Content of the message
assert.ok(msg.getMessage().getConversation(), 'tttest')
